name: main pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]
  
jobs:
  
  short:
    runs-on: ubuntu-latest
    outputs:
      SHORT_SHA: ${{ steps.short-sha.outputs.SHORT_SHA }}
    steps:
      - name: short sha
        id: short-sha
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node_version: 20
      run_tests: true

  docker:
    needs: [build-test, short]
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: "my-app"
      #tags: sha-${{ needs.short.outputs.SHORT_SHA }}
      tags: |
        - latest
        - sha-${{ needs.short.outputs.SHORT_SHA }}
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    environment: production
    steps:
      
      - name: print
        run: |
          echo "Deploying image: ${{ needs.docker.outputs.image_url }} to production"
   